# Generated by Django 3.0.5 on 2020-07-18 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hrstaff',
            unique_together={('id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='principal',
            unique_together={('id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('reg_number', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('id', 'user')},
        ),
    ]
