# Generated by Django 3.0.5 on 2020-06-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gaurdian',
            new_name='guardian',
        ),
    ]
