# Generated by Django 3.0.5 on 2020-07-03 10:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='')),
                ('due_date_time', models.DateTimeField()),
                ('total_marks', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'Assignment',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=30)),
                ('student_capacity', models.IntegerField(default=30)),
                ('incharge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Teacher')),
            ],
            options={
                'verbose_name': 'Class Room',
                'verbose_name_plural': 'Class Rooms',
                'db_table': 'ClassRoom',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sports Day', max_length=50)),
                ('detail', models.TextField(default='')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('fee', models.FloatField()),
                ('event_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.HrStaff')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'Exam',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'db_table': 'Level',
            },
        ),
        migrations.CreateModel(
            name='LevelSubjectTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Level')),
            ],
            options={
                'verbose_name': 'Level Subject Teacher',
                'verbose_name_plural': 'Level Subject Teachers',
                'db_table': 'LevelSubjectTeacher',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period', models.IntegerField(default=1, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'db_table': 'Period',
            },
        ),
        migrations.CreateModel(
            name='PTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('agenda', models.TextField(max_length=1000)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.HrStaff')),
            ],
            options={
                'verbose_name': 'Parent Teacher Meeting',
                'verbose_name_plural': 'Parent Teacher Meetings',
                'db_table': 'PTM',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.ClassRoom')),
                ('level_subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.LevelSubjectTeacher')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Period')),
            ],
            options={
                'verbose_name': 'Time Table',
                'verbose_name_plural': 'Time Tables',
                'db_table': 'TimeTable',
                'unique_together': {('class_room', 'level_subject_teacher'), ('period', 'class_room')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_wise_content', models.TextField(max_length=1000)),
                ('level_subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.LevelSubjectTeacher')),
            ],
            options={
                'verbose_name': 'Syllabus Planning',
                'verbose_name_plural': 'Syllabus Planning',
                'db_table': 'SyllabusPlanning',
            },
        ),
        migrations.CreateModel(
            name='SubjectTeachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher')),
            ],
            options={
                'verbose_name': 'Subject Teacher',
                'verbose_name_plural': 'Subject Teachers',
                'db_table': 'SubjectTeacher',
                'unique_together': {('subject', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='StudentLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
            options={
                'verbose_name': 'Student Leave',
                'verbose_name_plural': 'Student Leaves',
                'db_table': 'StudentLeave',
            },
        ),
        migrations.CreateModel(
            name='StudentComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('detail', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher')),
            ],
            options={
                'verbose_name': 'Student Complaint',
                'verbose_name_plural': 'Student Complaints',
                'db_table': 'StudentComplaint',
            },
        ),
        migrations.CreateModel(
            name='ParentComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('A', 'Addressed'), ('P', 'Pending')], default='P', max_length=1)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Parent')),
            ],
            options={
                'verbose_name': 'Parent Complaint',
                'verbose_name_plural': 'Parent Complaints',
                'db_table': 'ParentComplaint',
            },
        ),
        migrations.AddField(
            model_name='levelsubjectteacher',
            name='subject_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.SubjectTeachers'),
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('hrStaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.HrStaff')),
                ('student_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.StudentComplaint')),
            ],
            options={
                'verbose_name': 'Fine',
                'verbose_name_plural': 'Fines',
                'db_table': 'Fine',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_month_fee', models.FloatField()),
                ('fee_status', models.CharField(choices=[('D', 'Due'), ('P', 'Paid')], default='D', max_length=1)),
                ('fee_deposit_date', models.DateField()),
                ('fee_month', models.DateField(auto_now_add=True)),
                ('fine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.Fine')),
                ('hrStaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.HrStaff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
                'db_table': 'Fee',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField()),
                ('obtained_marks', models.FloatField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Subject')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exams Results',
                'db_table': 'ExamResult',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Level'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Subject'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Level'),
        ),
        migrations.CreateModel(
            name='AssignmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.FloatField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Subject')),
            ],
            options={
                'verbose_name': 'Assignment Result',
                'verbose_name_plural': 'Assignments Results',
                'db_table': 'AssignmentResult',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.ClassRoom'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='level_subject_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.LevelSubjectTeacher'),
        ),
        migrations.CreateModel(
            name='TeacherCalledForPTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.PTM')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Called For Meeting',
                'verbose_name_plural': 'Teachers Called For Meetings',
                'db_table': 'TeacherCalledForPTM',
                'unique_together': {('ptm', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], default='P', max_length=1)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teachers Attendance',
                'db_table': 'TeacherAttendance',
                'unique_together': {('teacher', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], default='P', max_length=1)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student', verbose_name='Student')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Teacher')),
            ],
            options={
                'verbose_name': 'Students Attendance',
                'verbose_name_plural': 'Students Attendance',
                'db_table': 'StudentAttendance',
                'unique_together': {('roll_number', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ParentCalledForPTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Parent')),
                ('ptm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.PTM')),
            ],
            options={
                'verbose_name': 'Parents Called For Meeting',
                'verbose_name_plural': 'Parents Called For Meetings',
                'db_table': 'ParentCalledForPTM',
                'unique_together': {('ptm', 'parent')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='levelsubjectteacher',
            unique_together={('subject_teacher', 'level')},
        ),
        migrations.CreateModel(
            name='HrStaffAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Leave')], default='P', max_length=1)),
                ('hrStaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.HrStaff')),
            ],
            options={
                'verbose_name': 'Hr Staff Attendance',
                'verbose_name_plural': 'Hr Staff Attendance',
                'db_table': 'HrStaffAttendance',
                'unique_together': {('hrStaff', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('date_time', 'level'), ('level', 'subject')},
        ),
        migrations.CreateModel(
            name='EventInvites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.Event')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Parent')),
            ],
            options={
                'verbose_name': 'Event Invites',
                'verbose_name_plural': 'Event Invites',
                'db_table': 'EventInvites',
                'unique_together': {('parent', 'event')},
            },
        ),
        migrations.CreateModel(
            name='DailyDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lesson_taught', models.TextField(max_length=1000)),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.TimeTable')),
            ],
            options={
                'verbose_name': 'Daily Diary',
                'verbose_name_plural': 'Daily Diaries',
                'db_table': 'DailyDiary',
                'unique_together': {('date', 'time_table')},
            },
        ),
        migrations.CreateModel(
            name='ClassRoomStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default=2020, max_length=4)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campus.ClassRoom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Student')),
            ],
            options={
                'verbose_name': 'Class Students',
                'verbose_name_plural': 'Class Students',
                'db_table': 'ClassRoomStudents',
                'unique_together': {('student', 'session')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('title', 'class_room'), ('title', 'level_subject_teacher')},
        ),
    ]
