# Generated by Django 3.0.5 on 2020-07-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomstudents',
            name='class_room',
            field=models.ForeignKey(error_messages={'required': 'this field is required'}, on_delete=django.db.models.deletion.DO_NOTHING, to='campus.ClassRoom'),
        ),
    ]
