# Generated by Django 3.0.4 on 2020-09-08 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_auto_20200725_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomstudents',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campus.ClassRoom'),
        ),
    ]
